Needs MODULES=lang/python; otherwise python2 gets picked up if present at configure time and the build breaks.
checking for python2... /usr/local/bin/python2
checking for python version... 2.7
<...>
/usr/local/bin/python2 -B ../data/templates/libkkc-data/tools/sortlm.py \
  ./data/models/text2/data.arpa data/models/sorted2/data
Traceback (most recent call last):
  File "../data/templates/libkkc-data/tools/sortlm.py", line 20, in <module>
    import marisa
ImportError: No module named marisa