hgview has been broken since August. repo.join has been deprecated since Mercurial 4.2.
Reported by landry@:
for l in (self.repo.sjoin('lock'), self.repo.join('wlock')):
AttributeError: 'localrepository' object has no attribute 'join'

While here, update to 1.9.0.

OK landry@. "go ahead" edd@ (MAINTAINER).

Remove edd@ as maintainer at his request.