Update to librsvg-2.59.2.
Explicitely link with libc++abi to prevent undefined reference to _Unwind_Resume
and friends.

Don't make the pc file relocatable, our buggy pkg-config(1) does not support the
pcfiledir variable.