unbreak libnettle on powerpc* by reverting a commit which incorrectly checked for __GLIBC_PREREQ() being available.
furthermore, for powerpc64 we need to disable the generated assembler code for
it fails to assemble with llvm:

  error: unexpected token at start of statement: .0:

that is to be revisited but for now libnettle (and thus gnutls) can be built again.

ok aja@ (MAINTAINER)