add NOT_FOR_ARCHS, no longer builds on i386 and unlikely on 32-bit arm
# gitea.dev/vendor/modernc.org/sqlite/lib
vendor/modernc.org/sqlite/lib/sqlite.go:161:15: undefined: TBitvec
vendor/modernc.org/sqlite/lib/sqlite.go:165:17: undefined: TBtCursor
vendor/modernc.org/sqlite/lib/sqlite.go:173:21: undefined: TBtreePayload
vendor/modernc.org/sqlite/lib/sqlite.go:428:18: undefined: TCallCount
[..]