splitmix64.h:14: error: expected '=', ',', ';', 'asm' or '__attribute__' befor e 'uint64_t'
Move to ports-gcc on base-gcc arches to fix build on sparc64