Drop chunk 7 of patch-GNUmakefile_in, it was added for webkit 2.0.0 at that time to workaround a gmake weirdness triggering forkbombs, but now apparently it causes weird build failures with binutils error messages when using MAKE_JOBS>=4, as experienced by sthen@, naddy@ & espie@.
Unfortunately, i don't have hardware with 4 cores or more, so didnt see
those... Removing the chunk doesnt seem to show gmake weirdness anymore,
 so just do it (tm). Analysed by espie@.

Note that gtk3 FLAVOR is broken on powerpc with "undefined reference to
`__atomic_fetch_add_8'". /me goes crying in a corner.

building webkit is hard, let's go shopping.