www/mozilla: set MODCLANG_VERSION to 16 to build with devel/llvm/16
since base switched to llvm 16, lld fails to link libxul.so with 'LLVM
ERROR: Cannot select: intrinsic %llvm.x86.sse42.crc32.64.64'.

upgrading wasi-compiler-rt to 16 & switching to build with ports-clang
16 instead of 13 (the default) fixes the build.