espeak: work around build failure on !lld archs, ok sthen
audio/espeak doesn't build on sparc64 due to what looks like a bug
in either base libtool or ld.bfd. libtool eats -L options for the
ld.so search directories in the ldconfig -r output, which then causes
linking failures. Work around this by switching to GNU libtool on the
affected architectures.

/usr/bin/libtool  --tag=CXX   --mode=link c++  -O2 -pipe -static -lm -lpcaudio  -L/usr/local/lib -L/usr/X11R6/lib -o src/speak-ng src/speak-ng.o src/libespeak-ng.la
...
libtool: link: c++ -o src/.libs/speak-ng -pthread -O2 -pipe src/speak-ng.o -Lsrc/.libs -lm -lpcaudio -lpulse-simple -lpulse -logg -lvorbis -lpthread -liconv /usr/obj/ports/espeak-1.52.0/espeak-ng-1.52.0/src/.libs/libespeak-ng.a -Wl,-rpath-link,/usr/local/lib
[...]
/usr/bin/ld: warning: libxcb.so.4.1, needed by src/.libs/libpcaudio.so.0.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXau.so.10.0, needed by src/.libs/libpcaudio.so.0.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXdmcp.so.11.0, needed by src/.libs/libpcaudio.so.0.1, not found (try using -rpath or -rpath-link)
/usr/local/lib/pulseaudio/libpulsecommon-17.0.so: undefined reference to `xcb_intern_atom_reply'
/usr/local/lib/pulseaudio/libpulsecommon-17.0.so: undefined reference to `xcb_disconnect'
...
Error while executing c++ -o src/.libs/speak-ng -pthread -O2 -pipe src/speak-ng.o -Lsrc/.libs -lm -lpcaudio -lpulse-simple -lpulse -logg -lvorbis -lpthread -liconv /usr/obj/ports/espeak-1.52.0/espeak-ng-1.52.0/src/.libs/libespeak-ng.a -Wl,-rpath-link,/usr/local/lib

https://cranky.work/sparc64/2025-11-11/audio/espeak.log