cyrus-sasl2: fix build with llvm22, ok ajacoutot naddy
Switch from hand-rolled memset(3) and memcpy(3) to the ones in libc.
The versions inherited from libdes abuse unsigned char * for void *
and [-Wincompatible-pointer-types] is now an error:

md5.c:400:14: error: incompatible pointer types passing 'unsigned char (*)[65]' to parameter of type 'POINTER' (aka 'unsigned char *') [-Wincompatible-pointer-types]

Switching POINTER to void * causes other problems.