fix the build of u-boot on big endian hosts
u-boot contains a static crc table with endian calls which requires the
endian calls to be macros.

lib/crc32.c:87: error: braced-group within expression allowed only inside a function

Define the glibc names in u-boot compiler.h as at least some parts of
the non-cross build assumes those names are present (ie crc32.c).

ok jca@