Fix most tests by cherrypicking https://github.com/eqrion/cbindgen/pull/557
test result: FAILED. 97 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out

of all the remaining failures, 6 of them are due to 'error: the option
`Z` is only accepted on the nightly compiler', the only real error
standing out is test_enum from a macro definition conflict ?

error: expected parameter declarator
static_assert(offsetof(CBINDGEN_STRUCT(P), tag) == 0,"unexpected offset for tag");
/usr/include/stddef.h:69:32: note: expanded from macro 'offsetof'
#define offsetof(type, member)  __builtin_offsetof(type, member)