devel/cutter: fix build on 32-bit arches.
When updating cutter, I had accidentally removed a thought "no longer needed"
patch. This commit adds it back with a comment to hopefully ensure it doesn't
happen again.

Fixes:

```
/pobj/cutter-2.1.0/cutter-2.1.0/src/widgets/GraphGridLayout.cpp:559:28: error: non-constant-expression cannot be narrowed from type 'const unsigned long long' to 'size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
        events.push_back({ it.first, 0, it.second.row, Event::Block });
                           ^~~~~~~~
```

OK sthen@, thanks.