Make nagios start up out of the box again after 'pkg_add nagios'.
Executables were installed mode 774 owned by root:bin. We need to use
mode 775 (o+x), otherwise nagios which runs as user _nagios complains:
  Error: failed to access() /usr/local/bin/nagios: Permission denied
  Error: Spawning workers will be impossible. Aborting.

Solution discussed and found together with sthen and tb.
ok sthen@ tb@