re2: fix build on sparc64
This needs the usual abseil-cpp workaround

CXXFLAGS_ports-gcc = -fdelete-null-pointer-checks

due to

/usr/local/include/absl/container/internal/hash_policy_traits.h:158:66: error: '(absl::lts_20260107::container_internal::TypeErasedApplyToSlotFn<absl::lts_20260107::hash_internal::Hash<long long unsigned int>, long long unsigned int, true> == 0)' is not a constant expression
  158 |     return Policy::template get_hash_slot_fn<Hash, kIsDefault>() == nullptr
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~