Build on sparc64 fails with:
cc -std=gnu99 -Iobj -I.  -O2 -pipe -I/usr/local/include -pthread -fno-strict-aliasing -fno-strict-overflow -MMD -MP -o obj/lib/blake2s.o -c lib/blake2s.c
lib/blake2s.c:45: error: expected declaration specifiers or '...' before 'sizeof'
lib/blake2s.c:45: error: expected declaration specifiers or '...' before string constant
lib/blake2s.c:45: warning: data definition has no type or storage class
lib/blake2s.c:45: warning: type defaults to 'int' in declaration of '_Static_assert'
gmake: *** [Makefile:112: obj/lib/blake2s.o] Error 1

Switch to ports-gcc on base-gcc arches

Fixes the build on sparc64