cgames: switch from int to short twice to fix build with llvm22
userio.c:398:2: error: incompatible pointer types passing 'int *' to parameter of type 'short *' [-Wincompatible-pointer-types]
  398 |         attr_get(&attr, &n, NULL);