Drop www/canto, fails at runtime, python2 only and unmaintained upstream
Fails at runtime with the following error:
NameError: name 'SET_VERSION_TUPLE' is not defined
because the installed .pyc is based on sources intended to be patched at
install time.

Removing canto removes one of the blockers for updates of feedparser and
chardet to python3-only versions.  Upstream has moved its efforts to
another project, canto-next, with python3 support and separate
daemon/client projects.

ok danj@ sthen@