Yet another bunch of ports that reliably fail to build on hppa.
BROKEN-hppa =	SIGILL when running lilypond
BROKEN-hppa =	libjson-c.so.0.0: undefined reference to __sync_val_compare_and_swap_4
BROKEN-hppa=	missing atomic ops
BROKEN-hppa=	./iodev/hdimage/hdimage.cc:807: error: 'bx_bswap32' was not declared in this scope
BROKEN-hppa =	cc1plus: error: unrecognized command line option '-std=c++11'
BROKEN-hppa =	src/bin/jp2/convert.c:192: error: expected identifier or '(' before '__extension__'
BROKEN-hppa=	libpt.so.7.0: undefined reference to __sync_fetch_and_or_4
BROKEN-hppa=	ykpers-json.c:42: error: redefinition of typedef 'json_bool'
BROKEN-hppa=	OOM on src/lxml/lxml.etree.c
BROKEN-hppa =	undefined reference to `__sync_val_compare_and_swap_4' in libjson-c
BROKEN-hppa =	rake fails when linking PassengerHelperAgent
BROKEN-hppa =	kstars/kstars/tools/scriptbuilder.cpp:103: internal compiler error: Segmentation fault
BROKEN-hppa=	build stuck on virt-viewer-window.c

See http://build-failures.rhaalovely.net/hppa/