py-matplotlib: disable link-time optimization for ports-gcc, ok daniel
The combination of a modern compiler with antique binutils isn't expected
in the ecosystem. On sparc64, LTO is enabled because the ports-gcc supports
it which then emits "e" sections which are to be excluded from executables
and shared objects by the link editor, such as

.section        .gnu.lto_.profile.5712db33fb59d8ee,"e",@progbits

As reported by kmos, Fred Flintstone's gas trips over these with

Fatal error: unrecognized .section attribute: want a,w,x,M,S,G,T