seamonkey: unbreak build with libcxx22, discussed with landry
hunspell_fopen_hooks.h contains a preprocessor hack to replace the standard
fopen() with one supporting readahead. This used to work because libcxx's
fstream header used a naked fopen() call. libcxx22 changed to std::fopen(),
so the build breaks because there is no std::hunspell_fopen_readahead():

/usr/include/c++/v1/fstream:716:20: error: no member named 'hunspell_fopen_readahead' in namespace 'std'; did you mean simply 'hunspell_fopen_readahead'?
  716 |   return __do_open(std::fopen(__s, __mdstr), __mode);