www/ruby-capybara-webkit: @comment .qmake.stash, ok jeremy sthen
I ran into a package build failure since that file wasn't generated for
some reason; there's no point in packaging it anyway.

===>  Building package for ruby30-capybara-webkit-1.15.0p1
Create /data/packages/amd64/all/ruby30-capybara-webkit-1.15.0p1.tgz
Creating package ruby30-capybara-webkit-1.15.0p1
[...]
Error: /tmp/pobj/capybara-webkit-1.15.0-ruby30/fake-amd64-ruby30/usr/local/lib/ruby/gems/3.0/ge
ms/capybara-webkit-1.15.0/.qmake.stash does not exist
pkg_create: can't continue