it's a nono on i386
tvram.cpp:254:5: error: unknown type name '__m128i'
tvram.cpp:258:9: error: use of undeclared identifier '_mm_set_epi32'
tvram.cpp:358:5: error: unknown type name '__m128i'
tvram.cpp:358:21: error: use of undeclared identifier '_mm_set_epi8'
etc.

+BROKEN-i386=           requires __m128i and similar types; may work if SSE is disabled