devel/libgee needs to use ports-gcc on base-gcc arches. Otherwise it dies with:
task.c:59: error: initializer element is not constant

Fixes the build on sparc64