use DPB_PROPERTIES=nojunk; mlpack uses setuptools without using MODPY_SETUPTOOLS so it doesn't pick up nojunk from python.port.mk
setuptools can pick up importlib_metadata if present at runtime,
if it's junked at the wrong point we can get "AttributeError: module
'importlib_metadata' has no attribute 'MetadataPathFinder'" (as
reported by aja@)

This can probably go away after switching to Python 3.10 by default