cc -O2 -pipe    -c main.c main.c: In function 'alarmInterrupt': main.c:40: error: parameter name omitted
Moving to ports-gcc on base-gcc arches fixes build on sparc64