emulators/citra: mark BROKEN
After net/nheko is now the second port that breaks in a mysterious way
due to a bad interaction of <locale> with <stdarg.h>.

In file included from /tmp/pobj/citra-0.0.0.1827/citra-unified-source-20230110-ad2cbe2/externals/dyn
armic/src/dynarmic/frontend/A32/a32_types.cpp:9:
In file included from /usr/include/c++/v1/ostream:140:
In file included from /usr/include/c++/v1/locale:218:
/usr/include/c++/v1/__bsd_locale_fallbacks.h:110:5: error: cannot initialize a parameter of type '__
va_list_tag *' with an lvalue of type 'va_list' (aka '__va_list_tag[1]')
    va_start(__va, __format);
    ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/stdarg.h:34:47: note: expanded from macro 'va_start'
#define va_start(ap, last)      __builtin_va_start((ap), last)
                                                   ^~~~